name = "liv3d Quickjoin"
modname = "liv3dquickjoin"
prefix = "liv3dquickjoin"
author = "liv3d / Crowdedlight"
mainprefix = "z"
sig_version = 3
reuse_private_key = true
files = [
  "mod.cpp",
  "logo_crow.paa",
  "liv3d_logo.paa",
  "README.md",
]
include = ["./include"]
exclude = [
  "*.psd",
  "*.png",
  "*.tga"
]
  
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"
  
releasebuild = [
  "@zip @liv3dquickjoin_{{version}}"
]
  
[header_exts]
version = "{{git \"id 8\"}}"
author = "liv3d / Crowdedlight"
